version: "3.1"
services:
# Official documentation: https://hub.docker.com/r/nextgenhealthcare/connect
  mc:
    image: nextgenhealthcare/connect:latest
    environment:
      - DATABASE=mysql
      - DATABASE_URL=jdbc:mysql://mariadb:3306/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=mirthuser
      - DATABASE_PASSWORD=mirthpassword
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx1024m
      - _MP_HTTPS_SERVER_PROTOCOLS='TLSv1.3,TLSv1.2'
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    depends_on:
      - mariadb

# Official documentation: https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MARIADB_USER=mirthuser
      - MARIADB_PASSWORD=mirthpassword
      - MYSQL_DATABASE=mirthdb
      - MYSQL_ROOT_HOST=%
    expose:
      - 3306

# Official documentation: https://hub.docker.com/_/vault
  # docker-compose example: https://github.com/hashicorp/vault-examples/blob/main/docker-compose.yml
  vault:
    image: vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8200:8200
    privileged: true